.\" Manpage for Library Staging Tool
.\" Contact dwherry2@my.apsu.edu for information about tool or assistance

.TH libstage 1 "19 August 2014" "1.0" "Tool Usage"

.SH NAME
.B libstage
\- Library Staging 

.SH SYNOPSIS
.B libstage
[OPTIONS]

.SH DESCRIPTION
.B libstage
is a tool designed to stage library files to Ramdisk in order to reduce filesystem bottlenecking due to network traffic

.SH OPTIONS
.IP -f,--filename
Specifies the path to the library file that needs to be staged to Ramdisk

.SH AUTHOR
.IP "Daniel Wherry (dwherry2@my.apsu.edu) - Department of Computer Science, Austin Peay State University"
